const times = [
    {
        "image": "./img/corinthians.png",
        "club": "Corinthians",
        "group": "Grupo A",
        "MP": 12,
        "W": 8,
        "D": 3,
        "L": 1,
        "GF": 20,
        "GA": 13,
        "GD": 7,
    },
    {
        "image": "./img/mirassol.png",
        "club": "Mirassol",
        "group": "Grupo A",
        "MP": 12,
        "W": 5,
        "D": 1, 
        "L": 6,
        "GF": 21,
        "GA": 21,
        "GD": 0,
    },
    {
        "image": "./img/botafogo.png",
        "club": "Botafogo",
        "group": "Grupo A",
        "MP": 12,
        "W": 2,
        "D": 5,
        "L": 5,
        "GF": 8,
        "GA": 13,
        "GD": -5,
    },
    {
        "image": "./img/internacional.png",
        "club": "Internacional",
        "group": "Grupo A",
        "MP": 12,
        "W": 0,
        "D": 7,
        "L": 5,
        "GF": 9,
        "GA": 19,
        "GD": -10,    },
    {
        "image": "./img/santos.png",
        "club": "Santos",
        "group": "Grupo B",
        "MP": 12,
        "W": 3,
        "D": 3,
        "L": 6,
        "GF": 15,
        "GA": 18,
        "GD": -3,
    },
    {
        "image": "./img/guarani.png",
        "club": "Guarani",
        "group": "Grupo B",
        "MP": 12,
        "W": 3,
        "D": 2,
        "L": 7,
        "GF": 12,
        "GA": 15,
        "GD": -3,
    },
    {
        "image": "./img/bragantino.png",
        "club": "Red Bull Bragantino",
        "group": "Grupo B",
        "MP": 12,
        "W": 3,
        "D": 2,
        "L": 7,
        "GF": 10,
        "GA": 16,
        "GD": -6,
    },
    {
        "image": "./img/portuguesa.png",
        "club": "Portuguesa",
        "group": "Grupo B",
        "MP": 12,
        "W": 2,
        "D": 5,
        "L": 5,
        "GF": 14,
        "GA": 17,
        "GD": -3,
    },
    {
        "image": "./img/sao_paulo.png",
        "club": "São Paulo",
        "group": "Grupo C",
        "MP": 12,
        "W": 5,
        "D": 4,
        "L": 3,
        "GF": 16,
        "GA": 12,
        "GD": 4,
    },
    {
        "image": "./img/novorizontino.png",
        "club": "Novorizontino",
        "group": "Grupo C",
        "MP": 12,
        "W": 3,
        "D": 6,
        "L": 3,
        "GF": 10,
        "GA": 10,
        "GD": 0,
    },
    {
        "image": "./img/noroeste.png",
        "club": "Noroeste",
        "group": "Grupo C",
        "MP": 12,
        "W": 2,
        "D": 4,
        "L": 6,
        "GF": 12,
        "GA": 17,
        "GD": -5,
    },
    {
        "image": "./img/agua_santa.png",
        "club": "Água Santa",
        "group": "Grupo C",
        "MP": 12,
        "W": 1,
        "D": 4,
        "L": 7,
        "GF": 9,
        "GA": 22,
        "GD": -13,    },
    {
        "image": "./img/sao_bernardo.png",
        "club": "São Bernardo",
        "group": "Grupo D",
        "MP": 12,
        "W": 8,
        "D": 1,
        "L": 3,
        "GF": 19,
        "GA": 14,
        "GD": 5,
    },
    {
        "image": "./img/ponte_preta.png",
        "club": "Ponte Preta",
        "group": "Grupo D",
        "MP": 12,
        "W": 6,
        "D": 4,
        "L": 2,
        "GF": 12,
        "GA": 7,
        "GD": 5,
    },
    {
        "image": "./img/palmeiras.png",
        "club": "Palmeiras",
        "group": "Grupo D",
        "MP": 12,
        "W": 5,
        "D": 5,
        "L": 2,
        "GF": 17,
        "GA": 9,
        "GD": 8,
    },
    {
        "image": "./img/velo_clube.png",
        "club": "Velo Clube",
        "group": "Grupo D",
        "MP": 12,
        "W": 3,
        "D": 3,
        "L": 6,
        "GF": 12,
        "GA": 17,
        "GD": -5,
    }
  ]
  
export default times;