export const gallery = [ 
    {
        "sec-title": " Galeria",
        "imagem": "http://localhost:3000/imgs/imgsCursos/cps1.jpg",
        "h3-imagem":"Centro Paula Souza",
        "p-imagem:": "Alunos Centro Paula Souza.",
        "img1": "http://localhost:3000/imgs/imgsCursos/cps2.jpg",
        "h3-1": "Centro Paula Souza",
        "p-1":"Galeria CPS.",
        "img2": "http://localhost:3000/imgs/imgsCursos/cps3.jpg",
        "h3-2": "Centro Paula Souza",
        "p-2":"Professor mais antigo do CPS.",
        "img3": "http://localhost:3000/imgs/imgsCursos/cps4.jpg",
        "h3-3": "Centro Paula Souza",
        "p-3":"Governador recebe intercâmbistas no Pálacio dos Bandeirantes.",
        "img4": "http://localhost:3000/imgs/imgsCursos/cps5.jpg",
        "h3-4": "Centro Paula Souza",
        "p-4":"Centro Paula Souza",
        "img5": "http://localhost:3000/imgs//imgsCursos/cps6.jpg",
        "h3-5": "Centro Paula Souza",
        "p-5":"Cafelândia.",
    },
    {
        "sec-title": " Galeria",
        "imagem": "http://localhost:3000/imgs/imgFofocas/fofoca4.png",
        "h3-imagem":"Centro Paula Souza",
        "p-imagem:": "Alunos Centro Paula Souza.",
        "img1": "http://localhost:3000/imgs/imgFofocas/fofoca1.jpg",
        "h3-1": "Centro Paula Souza",
        "p-1":"Galeria CPS.",
        "img2": "http://localhost:3000/imgs/imgFofocas/fofoca5.jpg",
        "h3-2": "Centro Paula Souza",
        "p-2":"Professor mais antigo do CPS.",
        "img3": "http://localhost:3000/imgs/imgFofocas/fofoca6.jpg",
        "h3-3": "Centro Paula Souza",
        "p-3":"Governador recebe intercâmbistas no Pálacio dos Bandeirantes.",
        "img4": "http://localhost:3000/imgs/imgFofocas/fofoca3.jpg",
        "h3-4": "Centro Paula Souza",
        "p-4":"Centro Paula Souza",
        "img5": "http://localhost:3000/imgs/imgFofocas/fofoca2.jpg",
        "h3-5": "Centro Paula Souza",
        "p-5":"Cafelândia.",
    },
    {
        "sec-title": " Galeria",
        "imagem": "http://localhost:3000/imgs/imgDtsC/junina1.jpg",
        "h3-imagem":"Centro Paula Souza",
        "p-imagem:": "Alunos Centro Paula Souza.",
        "img1": "http://localhost:3000/imgs/imgDtsC/junina2.jpg",
        "h3-1": "Centro Paula Souza",
        "p-1":"Galeria CPS.",
        "img2": "http://localhost:3000/imgs/imgDtsC/junina3.jpg",
        "h3-2": "Centro Paula Souza",
        "p-2":"Professor mais antigo do CPS.",
        "img3": "http://localhost:3000/imgs/imgDtsC/junina4.png",
        "h3-3": "Centro Paula Souza",
        "p-3":"Governador recebe intercâmbistas no Pálacio dos Bandeirantes.",
        "img4": "http://localhost:3000/imgs/imgDtsC/junina5.jpg",
        "h3-4": "Centro Paula Souza",
        "p-4":"Centro Paula Souza",
        "img5": "http://localhost:3000/imgs/imgDtsC/junina6.jpg",
        "h3-5": "Centro Paula Souza",
        "p-5":"Cafelândia.",
    },
    {
        "sec-title": " Galeria",
        "imagem": "http://localhost:3000/imgs/imgEventosC/parada3.jpg",
        "h3-imagem":"Centro Paula Souza",
        "p-imagem:": "Alunos Centro Paula Souza.",
        "img1": "http://localhost:3000/imgs/imgEventosC/parada2.jpg",
        "h3-1": "Centro Paula Souza",
        "p-1":"Galeria CPS.",
        "img2": "http://localhost:3000/imgs/imgEventosC/parada1.jpg",
        "h3-2": "Centro Paula Souza",
        "p-2":"Professor mais antigo do CPS.",
        "img3": "http://localhost:3000/imgs/imgEventosC/parada4.jpg",
        "h3-3": "Centro Paula Souza",
        "p-3":"Governador recebe intercâmbistas no Pálacio dos Bandeirantes.",
        "img4": "http://localhost:3000/imgs/imgEventosC/parada5.jpg",
        "h3-4": "Centro Paula Souza",
        "p-4":"Centro Paula Souza",
        "img5": "http://localhost:3000/imgs/imgEventosC/parada6.jpg",
        "h3-5": "Centro Paula Souza",
        "p-5":"Cafelândia.",
    },
    {
        "sec-title": " Galeria",
        "imagem": "http://localhost:3000/imgs/imgsCursos/curso1.jpg",
        "h3-imagem":"Centro Paula Souza",
        "p-imagem:": "Alunos Centro Paula Souza.",
        "img1": "http://localhost:3000/imgs/imgsCursos/curso2.jpg",
        "h3-1": "Centro Paula Souza",
        "p-1":"Galeria CPS.",
        "img2": "http://localhost:3000/imgs/imgsCursos/curso3.jpg",
        "h3-2": "Centro Paula Souza",
        "p-2":"Professor mais antigo do CPS.",
        "img3": "http://localhost:3000/imgs/imgsCursos/curso4.jpg",
        "h3-3": "Centro Paula Souza",
        "p-3":"Governador recebe intercâmbistas no Pálacio dos Bandeirantes.",
        "img4": "http://localhost:3000/imgs/imgsCursos/curso5.jpg",
        "h3-4": "Centro Paula Souza",
        "p-4":"Centro Paula Souza",
        "img5": "http://localhost:3000/imgs//imgsCursos/curso6.jpg",
        "h3-5": "Centro Paula Souza",
        "p-5":"Cafelândia.",
    },
]